
mat <- matrix(NA,ncol=5,nrow=24)
colnames(mat) <- c("PFT","PlantGrowthForm","LeafPhenology","LeafType","PhotosyntheticPathway")
# create Indeces
mat[1,1] <- "NeedleleafEvergreenTree"
  mat[1,2] <- "tree"
  mat[1,3] <- "evergreen"
  mat[1,4] <- "needleleaved"
mat[2,1] <- "NeedleleafDeciduousTree"
  mat[2,2] <- "tree"
  mat[2,3] <- "deciduous"
  mat[2,4] <- "needleleaved"
mat[3,1] <- "BroadleafEvergreenTree"
  mat[3,2] <- "tree"
  mat[3,3] <- "evergreen"
  mat[3,4] <- "broadleaved"
mat[4,1] <- "BroadleafDeciduousTree"
  mat[4,2] <- "tree"
  mat[4,3] <- "deciduous"
  mat[4,4] <- "broadleaved"

mat[5,1] <- "BroadleafDeciduousShrub"
  mat[5,2] <- "shrub"
  mat[5,3] <- "deciduous"
  mat[5,4] <- "broadleaved"
mat[6,1] <- "NeedleleafDeciduousShrub"
  mat[6,2] <- "shrub"
  mat[6,3] <- "deciduous"
  mat[6,4] <- "needleleaved"
mat[7,1] <- "BroadleafEvergreenShrub"
  mat[7,2] <- "shrub"
  mat[7,3] <- "evergreen"
  mat[7,4] <- "broadleaved"
mat[8,1] <- "NeedleleafEvergreenShrub"
  mat[8,2] <- "shrub"
  mat[8,3] <- "evergreen"
  mat[8,4] <- "needleleaved"

mat[9,1] <- "C3Grass"
  mat[9,2] <- "graminoid"
  mat[9,5] <- "C3"
mat[10,1] <- "C4Grass"
  mat[10,2] <- "graminoid"
  mat[10,5] <- "C3"
mat[11,1] <- "CAM"
  mat[11,2] <- "graminoid"
  mat[11,5] <- "CAM"
  
mat[12,1] <- "BroadleafC3Herb"
  mat[12,2] <- "herb"
#  mat[12,3] <- "evergreen"
  mat[12,4] <- "broadleaved"
  mat[12,5] <- "C3"
mat[13,1] <- "BroadleafC4Herb"
  mat[13,2] <- "herb"
  #  mat[13,3] <- "evergreen"
  mat[13,4] <- "broadleaved"
  mat[13,5] <- "C4"
mat[14,1] <- "NeedleleafHerb"
  mat[14,2] <- "herb"
  #  mat[14,3] <- "evergreen"
  mat[14,4] <- "needleleaved"
#  mat[14,5] <- "C4"
mat[15,1] <- "BroadleafHerb"
  mat[15,2] <- "herb"
  #  mat[15,3] <- "evergreen"
  mat[15,4] <- "broadleaved"
  #  mat[15,5] <- "C4"

mat[16,1] <- "Climber"
  mat[16,2] <- "climber"
mat[17,1] <- "Fern"
  mat[17,2] <- "fern"
mat[18,1] <- "Moss"
  mat[18,2] <- "moss"

mat[19,1] <- "BroadleafDeciduousTree_Shrub"
  mat[19,2] <- "tree-shrub"
  mat[19,3] <- "deciduous"
  mat[19,4] <- "broadleaved"
  #  mat[19,5] <- "C4"
mat[20,1] <- "NeedleleafDeciduousTree_Shrub"
  mat[20,2] <- "tree-shrub"
  mat[20,3] <- "deciduous"
  mat[20,4] <- "needleleaved"
mat[21,1] <- "BroadleafEvergreenTree_Shrub"
  mat[21,2] <- "tree-shrub"
  mat[21,3] <- "evergreen"
  mat[21,4] <- "broadleaved"
mat[22,1] <- "NeedleleafEvergreenTree_Shrub"
  mat[22,2] <- "tree-shrub"
  mat[22,3] <- "evergreen"
  mat[22,4] <- "needleleaved"

mat[23,1] <- "BroadleafTree"
  mat[23,2] <- "tree"
  mat[23,4] <- "broadleaved"
mat[24,1] <- "BroadleafHerb"
  mat[24,2] <- "herb"
  mat[24,4] <- "broadleaved"

  mat[order(mat[,2]),]
  require(xtable)
print(xtable(mat),include.rownames = FALSE)  
